### ISSUE TITLE
Chords for Corrobora need to be checked

### ISSUE THREAD

**Issue by daysm** [bahaisongproject/bahai-songs#2]
Compare with [video](https://www.youtube.com/watch?v=yRV5nuLqW-k) and [chord sheet](http://bahai-song-project.de/wp-content/uploads/PDF_corrobora.pdf).

**Comment by ChadSmithNet** [comment]
Guitar Pro and MP3 from Guitar Pro also available.
The last three notes are natural harmonics and strings 2, 3 and 4 on fret 5.

[Corrobora.pdf](https://github.com/daysm/bahai-songs/files/1882681/Corrobora.pdf)
[Corrobora.txt](https://github.com/daysm/bahai-songs/files/1881752/Corrobora.txt)

**Comment by ChadSmithNet** [comment]
Should I create a chord pro file?

**Comment by ChadSmithNet** [comment]
Still missing the strange chord towards the end.

**Comment by ChadSmithNet** [comment]
Updated the chord pro file but cannot make the PDF.

**Comment by daysm** [comment]
Cool! Thank you! Will update the PDF
