### ISSUE TITLE
He maketh victorious - Edim7 instead of E at the end

### ISSUE THREAD

**Issue by ChadSmithNet** [bahaisongproject/bahai-songs#4]
I believe JB Eckl plays Edim7 instead of E at the end of the song. Furthermore, although it looks like he plays a Bmin11 in the video and one would expect at least a Bmin, I believe it is just a B5 (X 2 4 4 0 X).
Should I correct it?

**Comment by daysm** [comment]
Yes, can you open a pull request?

**Comment by ChadSmithNet** [comment]
Ok

--  
Chad Smith

**Comment by ChadSmithNet** [comment]
Will open a pull request
